// <auto-generated />
using System;
using IrsiUtilities.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IrsiUtilities.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UtilitiesDbContext))]
    partial class UtilitiesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IrsiUtilities.Domain.Entities.ElectricityInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdditionalDemandCharge")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("AdditionalUsagekWh")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CeliRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CeliUse")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("CombustiblePurchased")
                        .HasColumnType("int");

                    b.Property<DateTime>("CurrentRead")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DemandCharge")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("EnergyPurchased")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("FixedCharge")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtherCharges")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("PreviousRead")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProvisionalTarif")
                        .HasColumnType("int");

                    b.Property<decimal>("RateAdditionalUsagekWh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RateCombustible")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RateEnergy")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RateProvisionalTarif")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("RatekWh")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ReadingType")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SubsidioHHRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SubsidioHHUse")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SubsidioNHHRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("SubsidioNHHUse")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("UsageDays")
                        .HasColumnType("int");

                    b.Property<decimal>("UsagekVA")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("UsagekWh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("ElectricityInvoices");
                });

            modelBuilder.Entity("IrsiUtilities.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CostCenter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("IrsiUtilities.Domain.Entities.WaterInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("CCARCharge")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CurrentRead")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FiscalPlanAdjustment")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.Property<DateTime>("PreviousRead")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReadingType")
                        .HasColumnType("int");

                    b.Property<decimal>("SpecialCharge")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StormDrainCharge")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Usage")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("UsageDays")
                        .HasColumnType("int");

                    b.Property<decimal>("WaterCharge")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("WaterInvoices");
                });

            modelBuilder.Entity("IrsiUtilities.Domain.Entities.ElectricityInvoice", b =>
                {
                    b.HasOne("IrsiUtilities.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IrsiUtilities.Domain.Entities.WaterInvoice", b =>
                {
                    b.HasOne("IrsiUtilities.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
